<div id="zox-feat-wrap" class="zoxrel">
	<?php $zox_skin = get_option('zox_skin'); $zox_feat_layout = get_option('zox_feat_layout'); $zox_cat_layout = get_option('zox_cat_layout'); if (($zox_skin == "5") || ($zox_skin == "6") || ($zox_skin == "7") || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "5" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "6" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "7" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "5" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "6" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "7" )) ) { ?>
		<?php get_template_part( 'parts/featured/feat', 'net' ); ?>
	<?php } else if (($zox_skin == "8") || ($zox_skin == "9") || ($zox_skin == "10") || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "8" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "9" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "10" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "8" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "9" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "10" )) ) { ?>
		<?php get_template_part( 'parts/featured/feat', 'sport' ); ?>
	<?php } else if (($zox_skin == "11") || ($zox_skin == "12") || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "11" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "12" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "11" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "12" )) ) { ?>
		<?php get_template_part( 'parts/featured/feat', 'fash' ); ?>
	<?php } else if (($zox_skin == "14") || ($zox_skin == "15") || ($zox_skin == "16") || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "14" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "15" )) || (is_front_page() && ( $zox_skin == "1" && $zox_feat_layout == "16" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "14" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "15" )) || (is_category() && ( $zox_skin == "1" && $zox_cat_layout == "16" )) ) { ?>
		<?php get_template_part( 'parts/featured/feat', 'tech' ); ?>
	<?php } else { ?>
		<?php get_template_part( 'parts/featured/feat', 'ent' ); ?>
	<?php } ?>
</div><!--zox-feat-wrap-->